social_company_blog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

social_company_blog/users/views.py
from crypt import methods
from dataclasses import dataclass
from fileinput import filename
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from social_company_blog import db
from social_company_blog.models import User, BlogPost
from social_company_blog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from social_company_blog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Log in success')
        
            next = request.args.get('next')

            if next == None or not next[0] =='/':
                next = url_for('core.index')
            
            return redirect(next)

    return render_template('login.html', form=form)

#logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account (update)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile+pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#user's list of blogposts
@users.route('/<username>')
def user_posts(username):
    
    # This allows us to cycle through pages of blog posts
    page = request.args.get('page', 1, type=int)
    
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

social_company_blog/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="container-md">
    <div class="bg-light p-5 rounded-lg m-3">
        <div align="center">
            <h1>Welcome to the page for {{current_user.username}}</h1>
            <img align="center" src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
        </div>
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="form-group">
        {{ form.username.label(class_="form-label") }}
        {{ form.username(class_="form-control") }}
        </div>
        
        <div class="form-group">
        {{ form.email.label(class_="form_label") }}
        {{ form.email(class_="form-control") }}
        </div>
        
        <div class="form-group">
        {{ form.picture.label(class_="form-label") }}
        {{ form.picture(class_="form-control") }}
        </div>
        
        <div class="form-group">
        {{ form.submit(class_="btn btn-primary") }}
        </div>
        
    </form>

{% endblock %}

social_company_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
    <title>Social Company Blog</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('core.index')}}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('core.info')}}">About</a>
                    </li>
                    {%  if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Create Post</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>

social_company_blog/templates/index.html
{% extends "base.html" %}
{% block content %}

    <div class="container-md">
        <div class="bg-light p-5 rounded-lg m-3">
        <h1>Social Company Blog</h1>
    </div>


{% endblock %}

social_company_blog/templates/info.html
{% extends "base.html" %}
{% block content %}
    
    <div class="container-md">
        <div class="bg-light p-5 rounded-lg m-3">
            <h1>Info about our company</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla assumenda reprehenderit consectetur? Aut deserunt iure ad minima enim. Mollitia, consequatur facilis qui aliquam voluptate consectetur quibusdam, reiciendis praesentium provident odio sequi nulla tempora tenetur illum quas error atque corporis! Ratione doloremque tempora hic ullam similique dolore? Non hic, consectetur, ducimus amet fugiat nobis eaque possimus quaerat omnis delectus harum, sint nam explicabo quae tempora sapiente optio? Dolore natus asperiores ab adipisci ullam quam repudiandae eligendi?</p>
        </div>
    </div>
{% endblock %}

social_company_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.submit()}}
    </form>

{% endblock %}

social_company_blog/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.username.label}}{{form.username}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
        {{form.submit()}}
    </form>

{% endblock %}

social_company_blog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
    <div class="container-md">
        <div class="bg-light p-5 rounded-lg m-3">
            <h1>Welcome to the page for {{ user.username }}</h1>
            <img src="{{ url_for('static', filename='profile_pics/'+user.profile_image)}}"/>
        </div>

        {% for post in blog_posts.items %}
            <h2>
                <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a>
            </h2>
            Written by: <a href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
            <p class="text-muted">Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
            <br/>
            <p>{{ post.text }}</p>
            <br/>
        {% endfor %}
    </div>

    <nav aria-label="Page Nav Example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if blog_posts.page == page_num %}
                    <li class="page-item disabled">
                        <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}"></a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}"></a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock content %}